### ISSUE TITLE
Issue with loader.py in Chapter 4

### ISSUE THREAD

**Issue by afettouhi** [foxbook/atap#101]
I am trying to get the code in loader.py to work with the latest scikit-learn package but I am having issues modifying KFold in order to get it to run. I have replaced cross_validation with the new model_selection submodule but I am unsure on how to modify KFold. I get this error currently:

```
/home/af/Dokumenter/Programs/miniconda3/envs/AppliedTextAnalysiswithPython/lib/python3.8/site-packages/sklearn/utils/validation.py:68: FutureWarning: Pass shuffle=12, random_state=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "
Traceback (most recent call last):
  File "/home/af/Dokumenter/Programs/AppliedTextAnalysiswithPython/Chapter 4/loader.py", line 61, in <module>
    loader = CorpusLoader(corpus, 12)
  File "/home/af/Dokumenter/Programs/AppliedTextAnalysiswithPython/Chapter 4/loader.py", line 13, in __init__
    self.folds = KFold(self.n_docs, folds, shuffle)
  File "/home/af/Dokumenter/Programs/miniconda3/envs/AppliedTextAnalysiswithPython/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/af/Dokumenter/Programs/miniconda3/envs/AppliedTextAnalysiswithPython/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 433, in __init__
    super().__init__(n_splits=n_splits, shuffle=shuffle,
  File "/home/af/Dokumenter/Programs/miniconda3/envs/AppliedTextAnalysiswithPython/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/af/Dokumenter/Programs/miniconda3/envs/AppliedTextAnalysiswithPython/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 288, in __init__
    raise TypeError("shuffle must be True or False;"
TypeError: shuffle must be True or False; got 12
```

**Comment by rebeccabilbro** [comment]
Hi there @afettouhi and thanks for checking out our book! I can't see your code, but your error message suggests that you need to make the positional argument a keyword argument when you instantiate the `CorpusLoader`. Try `loader = CorpusLoader(corpus, folds=12, shuffle=True)`. Hope that helps!

**Comment by afettouhi** [comment]
Thanks for the suggestion but this still fails with the same error. This the code I use for loader.py

```
from sklearn.model_selection import KFold


class CorpusLoader(object):

    def __init__(self, corpus, folds=None, shuffle=True):
        self.n_docs = len(corpus.fileids())
        self.corpus = corpus
        self.folds = folds

        if folds is not None:
            # Generate the KFold cross validation for the loader.
            self.folds = KFold(self.n_docs, folds, shuffle)

    @property
    def n_folds(self):
        """
        Returns the number of folds if it exists; 0 otherwise.
        """
        if self.folds is None:
            return 0
        return self.folds.n_folds

    def fileids(self, fold=None, train=False, test=False):

        if fold is None:
            # If no fold is specified, return all the fileids.
            return self.corpus.fileids()

        # Otherwise, identify the fold specifically and get the train/test idx
        train_idx, test_idx = [split for split in self.folds][fold]

        # Now determine if we're in train or test mode.
        if not (test or train) or (test and train):
            raise ValueError(
                "Please specify either train or test flag"
            )

        # Select only the indices to filter upon.
        indices = train_idx if train else test_idx
        return [
            fileid for doc_idx, fileid in enumerate(self.corpus.fileids())
            if doc_idx in indices
        ]

    def documents(self, fold=None, train=False, test=False):
        for fileid in self.fileids(fold, train, test):
            yield list(self.corpus.docs(fileids=fileid))

    def labels(self, fold=None, train=False, test=False):
        return [
            self.corpus.categories(fileids=fileid)[0]
            for fileid in self.fileids(fold, train, test)
        ]


if __name__ == '__main__':
    from reader import PickledCorpusReader

    corpus = PickledCorpusReader('../data/sample')
    loader = CorpusLoader(corpus, 12)

    for fid in loader.fileids(0, test=True):
        print(fid)
```

**Comment by rebeccabilbro** [comment]
In the code above, you are passing in `12` as a positional rather than a keyword argument

**Comment by afettouhi** [comment]
Yes, I am aware of that but this your original code from your github repo. The only change I have made is that cross_validation has been changed to model_selection since it has been deprecated.

**Comment by tsotman** [comment]
The parameters that sklearn KFold takes have changed in the more recent versions of scikit-learn. For example, the first parameter passed in your code is no longer included. The new KFold does not take a total number of elements parameter.

**Comment by tsotman** [comment]
Additionally, the new KFold returns an object with a few built in methods to get the splits, whereas the code above based on the old KFold relies on the return data type being an iterable itself. I would update the loader.py code, but I'm a newb.

New: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html#sklearn.model_selection.KFold

Old: https://scikit-learn.org/0.16/modules/generated/sklearn.cross_validation.KFold.html#sklearn.cross_validation.KFold

**Comment by bbengfort** [comment]
Perhaps this will work?

```python
class CorpusLoader(object):

    def __init__(self, corpus, folds=None, shuffle=True):
        self.n_docs = len(corpus.fileids())
        self.corpus = corpus
        self.folds = folds

        if folds is not None:
            # Generate the KFold cross validation for the loader.
            self.folds = KFold(n_splits=folds, shuffle=shuffle)

    …

   def fileids(self, fold=None, train=False, test=False):

        if fold is None:
            # If no fold is specified, return all the fileids.
            return self.corpus.fileids()

        # Otherwise, identify the fold specifically and get the train/test idx
        train_idx, test_idx = [split for split in self.folds.split(self.corpus.fileids())][fold]

        ...
```

I haven't tested it, but I think that will conform to the new scikit-learn API (there are probably a few other places thing will need to be updated).

Perhaps for simplicity, it might be best to go back to the version of scikit-learn the book was written with:

```
$ pip install scikit-learn==0.18
```
