### ISSUE TITLE
Chapter 10 

### ISSUE THREAD

**Issue by SamehMannai** [foxbook/atap#89]
First of all, thanks for the book. It's very helpful. Following along in the Chapter 10 Chatbot example, I hit an error when runing the app (python app.py). Any ideas?

Thanks!

python app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 299-270-304
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [18/Jul/2019 15:04:37] "POST /chat HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\samehm\Documents\Multiprocessing_nlp\ch10\app.py", line 56, in chat
    recs, build_time = suggest_recipe(message)
  File "C:\Users\samehm\Documents\Multiprocessing_nlp\ch10\recommender.py", line 68, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\samehm\Documents\Multiprocessing_nlp\ch10\recommender.py", line 222, in suggest_recipe
    results = tree.query(query)
  File "C:\Users\samehm\Documents\Multiprocessing_nlp\ch10\recommender.py", line 205, in query
    wordpunct_tokenize(terms)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 300, in fit_transform
    return last_step.fit_transform(Xt, y, **fit_params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\decomposition\truncated_svd.py", line 174, in fit_transform
    " got %d >= %d" % (k, n_features))
ValueError: n_components must be < n_features; got 200 >= 8

**Comment by rebeccabilbro** [comment]
Hello there @SamehMannai and thank you so much for checking out our book! Thanks also for providing the stack trace for the error you were experiencing; it definitely helps a bit to figure out what's going on! The short answer is that, while it initially might appear to be a Flask error (since the error is bubbling up through the app), it's possible that the error is actually related to the corpus used to train your model. 

In seeing the error `ValueError: n_components must be < n_features; got 200 >= 8` and without knowing what your corpus is, my guess is that the corpus has too small of a vocabulary. In the book, our truncated singular value decomposition model [specifies the number of output features to be 200](https://github.com/foxbook/atap/blob/master/snippets/ch10/recommender.py#L188), which means that when we call `fit_transform` on the `Pipeline` and get to the [scikit-learn SVD](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html) step, it tries to decompose the normalized, vectorized corpus (which is assumed to be pretty high dimensional; as we discuss in the book, most corpora have many thousands or even millions of unique tokens/dimensions!) into only 200 dimensions. That dimensionality reduction is really helpful since it reduces noise and the complexity of the final model. However, if your corpus has fewer than 200 words in it, when you get to the dimensionality reduction step, scikit-learn raises an error that essentially says "I can't reduce that to 200 features!"

To resolve the error, you could remove the dimensionality reduction step or increase the corpus/vocabulary size; though if your corpus in fact has only 8 words, probably increasing the corpus/vocab size is your best bet! 

We hope this helps and again, thank you for reading the book!

**Comment by rebeccabilbro** [comment]
Hope the silence means that the suggestions helped out and you were able to move forward with your model training! I'll go ahead an archive this issue now  in case another reader encounters  similar issue in the future. Thanks again for checking out our book!

**Comment by SamehMannai** [comment]
Thank you very much! Your suggestions helped me to solve the problem. 
Thanks again for the book!
